/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.*;
import javax.swing.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;

/**
 *
 * @author shrin
 */
public class Artist extends javax.swing.JFrame {

    /**
     * Creates new form Artist
     */
    private static final String Username = "root";
    private static final String password ="shri@1234";
    private static final String dataConn = "jdbc:mysql://localhost:3306/artist";
    
    
    Connection sqlConn = null;
    PreparedStatement pst =null;
    ResultSet rs = null;
    int q,i,id,deleteItem;
    public Artist() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void upDateDB()
    {
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn,Username,password);
            pst = sqlConn.prepareStatement("select * from artist");
            
            
            rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            
            q = stData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)jTable2.getModel();
                    RecordTable.setRowCount(0);
            
            while(rs.next()){
                Vector columnData = new Vector();
                 for(i = 1; i<=q;i++)
                 {
                     columnData.add(rs.getString("Name"));
                     columnData.add(rs.getString("Phone_no"));
                     columnData.add(rs.getString("Address"));
                     columnData.add(rs.getString("Email_ID"));
                     columnData.add(rs.getString("Art_Type"));
                     
                 }
                 RecordTable.addRow(columnData);
                  
            }
             
                    
                    
                    
                    
                    
        }
         catch (Exception ex)
         {
             JOptionPane.showMessageDialog(null,ex);
         }
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtName = new javax.swing.JTextField();
        jtxtPhone_no = new javax.swing.JTextField();
        jtxtAddress = new javax.swing.JTextField();
        jtxtEmail_ID = new javax.swing.JTextField();
        jtxtArt_Type = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jdbnADD = new javax.swing.JButton();
        jdbnRESET = new javax.swing.JButton();
        jdbnEXIT = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Artist");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 0, 110, 48);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 62, 55, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Phone_no");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 91, 70, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 125, 62, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email_ID");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 159, 62, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Art_Type");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 198, 70, 20);

        jtxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNameActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtName);
        jtxtName.setBounds(178, 62, 260, 22);
        getContentPane().add(jtxtPhone_no);
        jtxtPhone_no.setBounds(178, 91, 260, 22);
        getContentPane().add(jtxtAddress);
        jtxtAddress.setBounds(178, 125, 260, 22);
        getContentPane().add(jtxtEmail_ID);
        jtxtEmail_ID.setBounds(178, 159, 260, 22);
        getContentPane().add(jtxtArt_Type);
        jtxtArt_Type.setBounds(178, 194, 260, 22);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Phone_no", "Address", "Email_ID", "Art_Type"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 230, 452, 402);

        jdbnADD.setText("ADD");
        jdbnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbnADDActionPerformed(evt);
            }
        });
        getContentPane().add(jdbnADD);
        jdbnADD.setBounds(510, 90, 72, 23);

        jdbnRESET.setText("RESET");
        jdbnRESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbnRESETActionPerformed(evt);
            }
        });
        getContentPane().add(jdbnRESET);
        jdbnRESET.setBounds(510, 130, 72, 23);

        jdbnEXIT.setText("EXIT");
        jdbnEXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbnEXITActionPerformed(evt);
            }
        });
        getContentPane().add(jdbnEXIT);
        jdbnEXIT.setBounds(510, 170, 72, 23);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\shrin\\Pictures\\gallery_display_background_12_vector_158738.jpg")); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 600, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNameActionPerformed
 private JFrame frame;
    private void jdbnEXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbnEXITActionPerformed
        frame = new JFrame("EXIT");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit","MySQL Connector",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {
           System.exit(0);
        }
    }//GEN-LAST:event_jdbnEXITActionPerformed

    private void jdbnRESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbnRESETActionPerformed
        jtxtName.setText("");
        jtxtPhone_no.setText("");
        jtxtAddress.setText("");
        jtxtEmail_ID.setText("");
        jtxtArt_Type.setText("");
    }//GEN-LAST:event_jdbnRESETActionPerformed

    private void jdbnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbnADDActionPerformed
      try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn,Username,password);
            pst = sqlConn.prepareStatement("insert into  artist(Name,Phone_no,Address,Email_ID,Art_Type)value(?,?,?,?,?)");
            
            pst.setString(1,jtxtName.getText());
            pst.setString(2,jtxtPhone_no.getText());
            pst.setString(3,jtxtAddress.getText());
            pst.setString(4,jtxtEmail_ID.getText());
            pst.setString(5,jtxtArt_Type.getText());
                
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Added");
            upDateDB();
    }                                          
catch (ClassNotFoundException ex){
    java.util.logging.Logger.getLogger(Artist.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
    
}
        catch (SQLException ex)
        {
            java.util.logging.Logger.getLogger(Artist.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
       
    
    }//GEN-LAST:event_jdbnADDActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        DefaultTableModel RecordTable = (DefaultTableModel)jTable2.getModel();
               int SelectedRows=jTable2.getSelectedRow();
               
               jtxtName.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
               jtxtPhone_no.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
               jtxtAddress.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
               jtxtEmail_ID.setText(RecordTable.getValueAt(SelectedRows, 4).toString());
               jtxtArt_Type.setText(RecordTable.getValueAt(SelectedRows, 5).toString());
    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Artist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Artist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Artist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Artist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Artist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton jdbnADD;
    private javax.swing.JButton jdbnEXIT;
    private javax.swing.JButton jdbnRESET;
    private javax.swing.JTextField jtxtAddress;
    private javax.swing.JTextField jtxtArt_Type;
    private javax.swing.JTextField jtxtEmail_ID;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtPhone_no;
    // End of variables declaration//GEN-END:variables
}
