/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author shrin
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jdbnOwner = new javax.swing.JButton();
        jdbnArtist = new javax.swing.JButton();
        jdbnAdmin = new javax.swing.JButton();
        jdbnCustomer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("WELCOME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 0, 180, 40);

        jdbnOwner.setBackground(new java.awt.Color(0, 255, 204));
        jdbnOwner.setText("Owner");
        jdbnOwner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbnOwnerActionPerformed(evt);
            }
        });
        getContentPane().add(jdbnOwner);
        jdbnOwner.setBounds(40, 60, 72, 23);

        jdbnArtist.setBackground(new java.awt.Color(51, 255, 204));
        jdbnArtist.setText("Artist");
        jdbnArtist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbnArtistActionPerformed(evt);
            }
        });
        getContentPane().add(jdbnArtist);
        jdbnArtist.setBounds(170, 60, 72, 23);

        jdbnAdmin.setBackground(new java.awt.Color(51, 255, 204));
        jdbnAdmin.setText("Admin");
        jdbnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbnAdminActionPerformed(evt);
            }
        });
        getContentPane().add(jdbnAdmin);
        jdbnAdmin.setBounds(320, 60, 72, 23);

        jdbnCustomer.setBackground(new java.awt.Color(51, 255, 204));
        jdbnCustomer.setText("Customer");
        jdbnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbnCustomerActionPerformed(evt);
            }
        });
        getContentPane().add(jdbnCustomer);
        jdbnCustomer.setBounds(460, 60, 82, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\shrin\\Pictures\\4c8cc5d1b85ca7357ab1e3f137fb7e2c.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 560, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jdbnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbnCustomerActionPerformed
         Customer ob=new Customer();
              ob.setVisible(true);
    }//GEN-LAST:event_jdbnCustomerActionPerformed

    private void jdbnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbnAdminActionPerformed
              Admin ob=new Admin();
              ob.setVisible(true);
    }//GEN-LAST:event_jdbnAdminActionPerformed

    private void jdbnOwnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbnOwnerActionPerformed
        Owner ob=new Owner();
              ob.setVisible(true);
    }//GEN-LAST:event_jdbnOwnerActionPerformed

    private void jdbnArtistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbnArtistActionPerformed
       Artist ob=new Artist();
       ob.setVisible(true);
    }//GEN-LAST:event_jdbnArtistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jdbnAdmin;
    private javax.swing.JButton jdbnArtist;
    private javax.swing.JButton jdbnCustomer;
    private javax.swing.JButton jdbnOwner;
    // End of variables declaration//GEN-END:variables
}
